### ISSUE TITLE
Change styles of the cards in the 'services' section.

### ISSUE THREAD

**Issue by yashsarnaik22** [yashsarnaik22/html-css-JS-practices#1]
- Make the cards look separated.
- Redefine margin and padding.
- make the images align in one line(horizontally).

**Comment by mgilberties** [comment]
Hi, can I have a go at this one please?

**Comment by yashsarnaik22** [comment]
ok I'll check! @mgilberties

**Comment by sarthakturkar75** [comment]
Can i also do this?

**Comment by yashsarnaik22** [comment]
go ahead @sarthakturkar75
