### ISSUE TITLE
Add a JavaScript functionality to the project .

### ISSUE THREAD

**Issue by yashsarnaik22** [yashsarnaik22/html-css-JS-practices#2]
- refer to the OLA official site. 
- -> https://www.olacabs.com/ 

- select a feature or functionality that can be implemented using JavaScript.
- create an issue and get assigned.

**Comment by sarthakturkar75** [comment]
can i also do this?

**Comment by yashsarnaik22** [comment]
yes @sarthakturkar75 give it a try.
