### ISSUE TITLE
Create a simple form to book a cab using JavaScript or jQuery.

### ISSUE THREAD

**Issue by yashsarnaik22** [yashsarnaik22/html-css-JS-practices#4]
- Refer the ola or uber website : https://www.olacabs.com/  -- https://www.uber.com/in/en/

- Use jQuery or JavaScript to create a simple form and form validation

- Add script, create **index.js** file 

- form should be responsive

Good luck.

**Comment by Adelabuadeleke** [comment]
hello, i'd love to work on this

**Comment by yashsarnaik22** [comment]
Go ahead @Adelabuadeleke 
assigning you.

**Comment by sarthakturkar75** [comment]
can i also do this?

**Comment by yashsarnaik22** [comment]
@sarthakturkar75 sure go ahead!
